[package]
name = "raknet-python"
version = "0.2.0"
edition = "2021"

[lib]
name = "raknet_python"
crate-type = ["cdylib"]

[dependencies]
rust-raknet = "0.11.0"
tokio = { version = "1", features = ["full"] }
pyo3 = { version = "0.16.4", features = ["extension-module"] }
lazy_static = "1"
